// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package node

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NodeInfoServiceClient is the client API for NodeInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeInfoServiceClient interface {
	GetNodeInfo(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
}

type nodeInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeInfoServiceClient(cc grpc.ClientConnInterface) NodeInfoServiceClient {
	return &nodeInfoServiceClient{cc}
}

func (c *nodeInfoServiceClient) GetNodeInfo(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, "/node.NodeInfoService/GetNodeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeInfoServiceServer is the server API for NodeInfoService service.
// All implementations must embed UnimplementedNodeInfoServiceServer
// for forward compatibility
type NodeInfoServiceServer interface {
	GetNodeInfo(context.Context, *NodeRequest) (*NodeResponse, error)
	mustEmbedUnimplementedNodeInfoServiceServer()
}

// UnimplementedNodeInfoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeInfoServiceServer struct {
}

func (*UnimplementedNodeInfoServiceServer) GetNodeInfo(context.Context, *NodeRequest) (*NodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (*UnimplementedNodeInfoServiceServer) mustEmbedUnimplementedNodeInfoServiceServer() {}

func RegisterNodeInfoServiceServer(s *grpc.Server, srv NodeInfoServiceServer) {
	s.RegisterService(&_NodeInfoService_serviceDesc, srv)
}

func _NodeInfoService_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeInfoServiceServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.NodeInfoService/GetNodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeInfoServiceServer).GetNodeInfo(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeInfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "node.NodeInfoService",
	HandlerType: (*NodeInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeInfo",
			Handler:    _NodeInfoService_GetNodeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}
